### ISSUE TITLE
The X11 connection broke: I/O error (code 1) on Github Actions

### ISSUE THREAD

**Issue by jacobszpz** [The-Compiler/pytest-xvfb#33]
## Bug description

My tests run smoothly locally, but on Github Actions there is an error after running, similar to #11.

```
======================== 40 passed, 17 skipped in 7.20s ========================
The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 0 (Success) on X server ":0"
      after 1378 requests (1369 known processed) with 0 events remaining.
```

## To Reproduce
I am not entirely sure but here is my GA workflow file:

```
name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python: [ "3.10" ]

    steps:
    - name: Get repository
      uses: actions/checkout@v3

    - name: Set up virtual X11
      run: sudo apt-get install xvfb

    - name: Set up PyQt dependencies
      uses: tlambert03/setup-qt-libs@v1

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Update pip and install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Freeze requirements
      run: pipenv requirements --dev > requirements.txt

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Install pytest-xvfb
      run: pip install pytest-xvfb

    # - name: Lint with flake8
    # run: |
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: xvfb-run -a pytest

```

## Expected behavior

The workflow to succeed.

## Additional context

My tests involve creating a QSystemTrayIcon which I can't use qtbot.addWidget with, so perhaps related to it?

## System information

ubuntu-latest
